### ISSUE TITLE
I have some doubts about the definition of 'mustKeep' because the value of variable x_i has not been determined on the path from r to n.

### ISSUE THREAD

**Issue by WaTerminator** [xgillard/ijcai_22_DDLNS#1]

**Comment by xgillard** [comment]
Would you mind elaborating a bit? I understand that something bothers you but I don't get your question... 

If interested, you can read the full paper in the proceedings of the ICAI conference of last year: https://www.ijcai.org/proceedings/2022/0659.pdf  There, you will find a formal definition of the mustkeep predicate (page 4 out of 7). 

Feel free to ask if anything is unclear.

Best

**Comment by WaTerminator** [comment]
Related part in the paper is "a node n from the ith layer must be kept if the value associated to variable xi on the best r − n path...". From the definition of the transition function, when we arrive at node n, we only have the value of x0, x1, ..., xi-1 since node n located at the ith layer. This makes me a little confused. Thanks for your explanation!

**Comment by xgillard** [comment]
Well, I guess it was nothing but a sloppy use of the term "ith layer". Indeed, the last paragraph from the 3rd page reads as follows: "As shown per Algorithm 4, one initially partitions the nodes of a given layer $L_i$ between those nodes which must be kept in the layer, and the others (Algorithm 4 lines 5-11). This decision is based on the mustKeep predicate (Definition 5.1) which states that a node $n$ from the ith layer (**understand from the layer $L_i$**) must be kept if the value associated to variable $x_i$ on the best r − n path (denoted p∗r−n(i)) is the same as the value of $x_i$ in s∗ (denoted s∗(i)). This guarantees that s∗ ∈ Sol(neighborhood) and hence that neighborhood is an actual neighborhood of s∗ (Algorithm 3 line 10)."

I hope it helps. If that very sentence is what bugged you, then you have my apologies: it should have read like so:
'This decision is based on the mustKeep predicate (Definition 5.1) which states that a node $n$ from the layer $L_i$ must be kept if the value associated to variable $x_i$ on the best r − n path' . 

In case of doubt, you may also want to double-check the code: it was made open source to make sure all doubts could be alleviated and the results could be reproduced.

Cheers,

**Comment by WaTerminator** [comment]
Thanks a lot for your reply!
I'm not very familiar with Rust, so I want to use the following two questions to check if I had understood correctly:
1. Does the "best r-n path" is exactly a part of s* or it is calculated during the construction of Restrict DD?
2. Does each layer only contains a single node satisfy "mustKeep"?

**Comment by xgillard** [comment]
Regarding (1): No, the best r-n path is not guaranteed to be a sub path of s*. A best r-n path really means a best partial assignment from the initial state, that leads to node n following the edges of the DD. The "best" here is really a notion local to node n. 

Regarding (2): No, each layer will likely contain many nodes satisfying the mustkeep predicate. Indeed, for it to be satisfied, it suffices that the decision about $x_i$ in the best path of node $n$ be the same as the decision that was made about $x_i$ in s*.

**Comment by WaTerminator** [comment]
Since n is in $L_i$, we know n belongs to $S_i$. From the following formulation, we know that the value of $x_i$ will be determined once we arrive at $L_{i+1}$, in other words, we don't know the value of $x_i$ at $L_i$, so it seems that we don't know the decision about $x_i$ in the path r - n. This is my most confusing point, may you explain it a little bit more?
Thanks a lot for your patient explanation!
![1NCJT)B@RN CS E$@CX9DXP](https://user-images.githubusercontent.com/58843099/231487520-aef09d9f-0908-4931-a457-645e4b391fb4.png)

**Comment by xgillard** [comment]
In the source code, you will find the following (taken from the PSP but that is the overall strategy):

```rust
fn is_mandatory<S: papier_lns::NodeSource>(
        &self,
        dd: &S,
        node: &S::Node,
        last_var: Var,
        best_sol: &Option<papier_lns::Solution>,
    ) -> bool {
        if let Some(best_sol) = best_sol {
            if let Some(last_decision) = dd.path(node).next() {
                let best_decision = best_sol[last_var];
                if last_decision.val == best_decision {
                    return true;
                }
            }
        }
        false
    }
}
```

From there you should understand that:
1. if there is no best known solution (no s*) then, no node is ever considered mandatory (mustKeep = false).
2. if there is not path to the `node` in question (only ever occurs for the root node) then it is not forced to be mandatory (the root node, however, is never going to be challenged since it is the root of the problem).
3. Otherwise, if the decision made about `last_var` (the last variable about which a decision was made) is the same in both the best known solution, and in the best path to `node`; then (and only then) is `node` considered mandatory.

Hence I hope it helps to clarify that the mustKeep predicate is an heuristic designed to guide the restrict procedure that is used to force the deletion of certain nodes when the mdd grows too large. That heuristic uses a simple rule to prevent the removal of certain nodes and that rule is that "if the latest decision on the best path to a node corresponds to the decision made about the same variable in the best known solution, then that node should not be deleted.


You do however have a point: I did mess up with the $i$ vs $i+1$ when working and reworking the text. As you correctly pointed out: $n_i \in L_i$, and the paragraph should read:
"As shown per Algorithm 4, one initially partitions the nodes of a given layer
$L_i$ between those nodes which must be kept in the layer, and
the others (Algorithm 4 lines 5-11). This decision is based on
the mustKeep predicate (Definition 5.1) which states that a
node $n \in L_i$ must be kept if the value associated
to variable $x_{i-1}$ on the best $r − n$ path ( denoted $p∗_{r−n}(i)$ ) is the
same as the value of $x_{i-1}$ in $s∗$ ( denoted $s∗(i)$ )."

Given these slight corrections, I don't believe that the defintion 5.1 needs to be changed though.

**Comment by WaTerminator** [comment]
Thanks a lot for such a detailed explanation!!!
I now believe I understand the whole method.
Since I will sooner make a presentation about this work to my friends, I need to check  whether I get the main point correctly : ).
Thank you for your help!
Best wishes!

**Comment by xgillard** [comment]
Don't hesitate to get in touch if you feel like it: I should still be able to retrieve the slides deck and poster I've used at IJCAI if that is of any use and interest.
